language : c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - autoreconf && ./configure                && automake && make
  - autoreconf && ./configure --with-threads && automake && make
