# FROM : https://github.com/tsoding/nothing/blob/master/appveyor.yml

image:
  - Ubuntu
  - MacOS
  - Visual Studio 2015

environment: # enable mingw build on windows image
  MSYSTEM: MINGW64
  CHERE_INVOKING: 1
  matrix:
    - BUILD_TYPE: mingw
    - BUILD_TYPE: other

matrix:
  exclude: # no mingw build on unix
    - image: Ubuntu
      BUILD_TYPE: mingw
    - image: MacOS
      BUILD_TYPE: mingw
    - image: Visual Studio 2015
      BUILD_TYPE: other

build_script:
  - ps: |
       if ($isWindows) {
           if ($env:BUILD_TYPE -eq 'mingw') {
              C:\msys64\usr\bin\bash -lc "aclocal"
              C:\msys64\usr\bin\bash -lc "autoupdate"
              C:\msys64\usr\bin\bash -lc "autoconf"
              C:\msys64\usr\bin\bash -lc "automake --add-missing"
              C:\msys64\usr\bin\bash -lc "./configure --with-threads"
              C:\msys64\usr\bin\bash -lc "make"
              C:\msys64\usr\bin\bash -lc "strip src/yass.exe"
              C:\msys64\usr\bin\bash -lc "mv -f src/yass.exe src/yass-Win64.exe"
           }
       } else {       
           if ($isLinux) {
               bash -c "sudo apt-get update"
               bash -c "sudo apt-get upgrade"
               bash -c "sudo apt-get install autotools-dev"
               bash -c "./configure --with-threads && make && strip src/yass"
               bash -c "mv -f src/yass src/yass-Linux64.bin"
           } else {
               bash -c "./configure --with-threads && make && strip src/yass"
               bash -c "mv -f src/yass src/yass-MacOS64.bin"
           }
       }

artifacts:
  - path: 'src\yass-*'
    name: Releases

deploy:
  provider: GitHub
  description: 'Mac OS X and Windows 64 binaries'
  release: ${APPVEYOR_REPO_TAG_NAME}
  auth_token:
    secure: a+NmYFzXxPCFefjxKpbBxgRjCUJTVBpQkPOyWV3/qXgp5/CB533quFGZh3j+3XOT
  #artifact: /yass-.*/
  draft: true
  prerelease: true

