# FROM : https://github.com/tsoding/nothing/blob/master/appveyor.yml

image:
  - Ubuntu
  - MacOS
  - Visual Studio 2015

environment: # enable mingw build on windows image
  MSYSTEM: MINGW64
  CHERE_INVOKING: 1
  matrix:
    - BUILD_TYPE: mingw
    - BUILD_TYPE: other

matrix:
  exclude: # no mingw build on unix
    - image: Ubuntu
      BUILD_TYPE: mingw
    - image: MacOS
      BUILD_TYPE: mingw
    - image: Visual Studio 2015
      BUILD_TYPE: other

build_script:
  - ps: |
       if ($isWindows) {
           if ($env:BUILD_TYPE -eq 'mingw') {
              C:\msys64\usr\bin\bash -lc "autoreconf"
              C:\msys64\usr\bin\bash -lc "./configure --with-threads"
              C:\msys64\usr\bin\bash -lc "make"
           }
       } else {
           bash -c "autoreconf && ./configure --with-threads && make"
       }
